// Mocks generated by Mockito 5.4.6 from annotations
// in earlybird/test/providers/listings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:earlybird/models/listing.dart' as _i6;
import 'package:earlybird/models/search_filter.dart' as _i5;
import 'package:earlybird/services/listing_storage_service.dart' as _i7;
import 'package:earlybird/services/scraper_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class MockScraperService extends _i1.Mock implements _i2.ScraperService {
  MockScraperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  List<String> get botProtectionBodyIndicators => (super.noSuchMethod(
        Invocation.getter(#botProtectionBodyIndicators),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get botProtectionPageTitle => (super.noSuchMethod(
        Invocation.getter(#botProtectionPageTitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#botProtectionPageTitle),
        ),
      ) as String);

  @override
  _i4.Future<List<Map<String, String>>> fetchListingHeadings(
          _i5.SearchFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchListingHeadings,
          [filter],
        ),
        returnValue: _i4.Future<List<Map<String, String>>>.value(
            <Map<String, String>>[]),
      ) as _i4.Future<List<Map<String, String>>>);

  @override
  _i4.Future<String> fetchListingImage(String? detailUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchListingImage,
          [detailUrl],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchListingImage,
            [detailUrl],
          ),
        )),
      ) as _i4.Future<String>);
}

class MockListingStorageService extends _i1.Mock
    implements _i7.ListingStorageService {
  MockListingStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(#init, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i6.Listing> getAllListings() => (super.noSuchMethod(
        Invocation.method(#getAllListings, []),
        returnValue: <_i6.Listing>[],
      ) as List<_i6.Listing>);

  @override
  List<_i6.Listing> getListingsForFilter(String? filterKey) =>
      (super.noSuchMethod(
        Invocation.method(#getListingsForFilter, [filterKey]),
        returnValue: <_i6.Listing>[],
      ) as List<_i6.Listing>);

  @override
  _i4.Future<void> saveListing(_i6.Listing? listing) => (super.noSuchMethod(
        Invocation.method(#saveListing, [listing]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveListings(List<_i6.Listing>? listings) =>
      (super.noSuchMethod(
        Invocation.method(#saveListings, [listings]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateListingViewedStatus(String? url, bool? isViewed) =>
      (super.noSuchMethod(
        Invocation.method(#updateListingViewedStatus, [url, isViewed]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleListingViewed(String? url, {bool? forceViewed}) =>
      (super.noSuchMethod(
        Invocation.method(
            #toggleListingViewed, [url], {#forceViewed: forceViewed}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i6.Listing> mergeWithCache(
          List<_i6.Listing>? newListings, String? filterKey) =>
      (super.noSuchMethod(
        Invocation.method(#mergeWithCache, [newListings, filterKey]),
        returnValue: <_i6.Listing>[],
      ) as List<_i6.Listing>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(#clearAll, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(#close, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
