// Mocks generated by Mockito 5.4.6 from annotations
// in earlybird/test/widgets/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:earlybird/models/listing.dart' as _i6;
import 'package:earlybird/models/search_filter.dart' as _i4;
import 'package:earlybird/models/site.dart' as _i9;
import 'package:earlybird/providers/listings_provider.dart' as _i5;
import 'package:earlybird/services/image_loader_service.dart' as _i3;
import 'package:earlybird/services/listing_storage_service.dart' as _i10;
import 'package:earlybird/services/scraper_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeScraperService_0 extends _i1.SmartFake
    implements _i2.ScraperService {
  _FakeScraperService_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeImageLoaderService_1 extends _i1.SmartFake
    implements _i3.ImageLoaderService {
  _FakeImageLoaderService_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSearchFilter_2 extends _i1.SmartFake implements _i4.SearchFilter {
  _FakeSearchFilter_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeListingStorageService_3 extends _i1.SmartFake
    implements _i10.ListingStorageService {
  _FakeListingStorageService_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class MockListingsProvider extends _i1.Mock implements _i5.ListingsProvider {
  MockListingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ScraperService get scraperService => (super.noSuchMethod(
        Invocation.getter(#scraperService),
        returnValue: _FakeScraperService_0(this, Invocation.getter(#scraperService)),
      ) as _i2.ScraperService);

  @override
  _i3.ImageLoaderService get imageLoaderService => (super.noSuchMethod(
        Invocation.getter(#imageLoaderService),
        returnValue: _FakeImageLoaderService_1(this, Invocation.getter(#imageLoaderService)),
      ) as _i3.ImageLoaderService);

  @override
  _i10.ListingStorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeListingStorageService_3(this, Invocation.getter(#storageService)),
      ) as _i10.ListingStorageService);

  @override
  List<_i6.Listing> get listings => (super.noSuchMethod(
        Invocation.getter(#listings),
        returnValue: <_i6.Listing>[],
      ) as List<_i6.Listing>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  bool get hasMore => (super.noSuchMethod(
        Invocation.getter(#hasMore),
        returnValue: false,
      ) as bool);

  @override
  _i4.SearchFilter get currentFilter => (super.noSuchMethod(
        Invocation.getter(#currentFilter),
        returnValue: _FakeSearchFilter_2(this, Invocation.getter(#currentFilter)),
      ) as _i4.SearchFilter);

  @override
  _i9.Site get selectedSite => (super.noSuchMethod(
        Invocation.getter(#selectedSite),
        returnValue: _i9.Site.funda,
      ) as _i9.Site);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> fetchListings() => (super.noSuchMethod(
        Invocation.method(#fetchListings, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadMore() => (super.noSuchMethod(
        Invocation.method(#loadMore, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateFilter(_i4.SearchFilter? newFilter) =>
      (super.noSuchMethod(
        Invocation.method(#updateFilter, [newFilter]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void selectSite(_i9.Site? site) => super.noSuchMethod(
        Invocation.method(#selectSite, [site]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> markAsViewed(_i6.Listing? listing) => (super.noSuchMethod(
        Invocation.method(#markAsViewed, [listing]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool shouldLoadMore(int? currentItemIndex) => (super.noSuchMethod(
        Invocation.method(#shouldLoadMore, [currentItemIndex]),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(#refresh, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(#addListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(#removeListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(#notifyListeners, []),
        returnValueForMissingStub: null,
      );
}
