// Mocks generated by Mockito 5.4.6 from annotations
// in earlybird/test/services/image_loader_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:earlybird/models/search_filter.dart' as _i5;
import 'package:earlybird/services/scraper_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ScraperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScraperService extends _i1.Mock implements _i2.ScraperService {
  MockScraperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  _i4.Future<List<Map<String, String>>> fetchListingHeadings(
          _i5.SearchFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchListingHeadings,
          [filter],
        ),
        returnValue: _i4.Future<List<Map<String, String>>>.value(
            <Map<String, String>>[]),
      ) as _i4.Future<List<Map<String, String>>>);

  @override
  _i4.Future<String> fetchListingImage(String? detailUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchListingImage,
          [detailUrl],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchListingImage,
            [detailUrl],
          ),
        )),
      ) as _i4.Future<String>);
}
